
spring.application.name=bidding
spring.data.mongodb.uri=mongodb+srv://eventbidding:eventbidding123@eventbidding.tmzdot1.mongodb.net/?appName=eventbidding
spring.data.mongodb.database=eventbidding
spring.data.mongodb.auto-index-creation=true